// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace CubicPilot.Behaviors
{
public static class GPGSIds
{
        public const string achievement_round_1 = "CgkIgqLAirYNEAIQDg"; // <GPGSID>
        public const string achievement_full_combo = "CgkIgqLAirYNEAIQAg"; // <GPGSID>
        public const string achievement_round_3 = "CgkIgqLAirYNEAIQEA"; // <GPGSID>
        public const string achievement_not_a_disaster = "CgkIgqLAirYNEAIQAA"; // <GPGSID>
        public const string achievement_captain = "CgkIgqLAirYNEAIQBg"; // <GPGSID>
        public const string achievement_perfect_accuracy = "CgkIgqLAirYNEAIQBA"; // <GPGSID>
        public const string achievement_time_play_level_1 = "CgkIgqLAirYNEAIQCw"; // <GPGSID>
        public const string achievement_time_play_level_2 = "CgkIgqLAirYNEAIQDA"; // <GPGSID>
        public const string achievement_time_play_level_3 = "CgkIgqLAirYNEAIQDQ"; // <GPGSID>
        public const string achievement_twofour = "CgkIgqLAirYNEAIQCQ"; // <GPGSID>
        public const string leaderboard_the_winners = "CgkIgqLAirYNEAIQEQ"; // <GPGSID>
        public const string achievement_round_2 = "CgkIgqLAirYNEAIQDw"; // <GPGSID>
        public const string achievement_clear_all_levels = "CgkIgqLAirYNEAIQAw"; // <GPGSID>
        public const string achievement_step_by_step = "CgkIgqLAirYNEAIQFA"; // <GPGSID>
        public const string achievement_sargent = "CgkIgqLAirYNEAIQBQ"; // <GPGSID>
        public const string achievement_dozen = "CgkIgqLAirYNEAIQCA"; // <GPGSID>
        public const string achievement_point_blank = "CgkIgqLAirYNEAIQAQ"; // <GPGSID>
        public const string achievement_tree_sick = "CgkIgqLAirYNEAIQCg"; // <GPGSID>
        public const string achievement_admiral = "CgkIgqLAirYNEAIQBw"; // <GPGSID>

}
}
