// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2014 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace SmokeTest
{
public static class GPGSIds
    {
        /*
         * This file is a placeholder to allow compilation of the sample code
         * The actual values are populated by the plugin when Setup is run
         * using the resource data from the Play Console.
         */
        public const string achievement_achievementtoincrement = "PLACEHOLDER - This file will be generated."; // <GPGSID>
        public const string achievement_achievementtounlock = "PLACEHOLDER - This file will be generated."; // <GPGSID>
        public const string achievement_achievementtoreveal = "PLACEHOLDER - This file will be generated."; // <GPGSID>
        public const string event_smokingevent = "PLACEHOLDER - This file will be generated."; // <GPGSID>
        public const string achievement_achievement_hidden_incremental = "PLACEHOLDER - This file will be generated."; // <GPGSID>
        public const string leaderboard_leaders_in_smoketesting = "PLACEHOLDER - This file will be generated."; // <GPGSID>
    }
}
