// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///
/// Keep the <GPGSID> tag on the line with the variable.  This is used
/// by the git hook to make sure real resource IDs are not checked in.

namespace CubicPilot
{
    public static class GPGSIds
    {
        public const string achievement_not_a_disaster = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_point_blank = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_full_combo = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_clear_all_levels = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_perfect_accuracy = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_sargent = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_captain = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_admiral = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_1_dozen_stars = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_two_dozen_stars = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_3_dozen_stars = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_five_minute_master = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_30_minutes_of_excitement = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_procrastinate_much = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_played_2_rounds = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_played_10_rounds = "PLACEHOLDER"; // <GPGSID>
        public const string achievement_played_25_rounds = "PLACEHOLDER"; // <GPGSID>
        public const string leaderboard_cubic_pilot_hall_of_fame = "PLACEHOLDER"; // <GPGSID>
    }
}
